import MainContextProvider from "@/context/mainContext";
import "./globals.css";
import Body from "@/components/layout/Body";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <MainContextProvider>
        <Body>
          {children}
        </Body>
      </MainContextProvider>
    </html>
  );
}
